In [ ]:
import pandas as pd


category_tree = pd.read_csv("../data/raw/category_tree.csv")
category_tree

      categoryid  parentid
0           1016     213.0
1            809     169.0
2            570       9.0
3           1691     885.0
4            536    1691.0
...          ...       ...
1664          49    1125.0
1665        1112     630.0
1666        1336     745.0
1667         689     207.0
1668         761     395.0

[1669 rows x 2 columns]

In [2]:
events = pd.read_csv("../data/raw/events.csv")
events

             timestamp  visitorid event  itemid  transactionid
0        1433221332117     257597  view  355908            NaN
1        1433224214164     992329  view  248676            NaN
2        1433221999827     111016  view  318965            NaN
3        1433221955914     483717  view  253185            NaN
4        1433221337106     951259  view  367447            NaN
...                ...        ...   ...     ...            ...
2756096  1438398785939     591435  view  261427            NaN
2756097  1438399813142     762376  view  115946            NaN
2756098  1438397820527    1251746  view   78144            NaN
2756099  1438398530703    1184451  view  283392            NaN
2756100  1438400163914     199536  view  152913            NaN

[2756101 rows x 5 columns]

In [ ]:
items_1= pd.read_csv("../data/raw/item_properties_part1.csv")items_1= pd.read_csv("../data/raw/item_properties_part1.csv")
items_1

              timestamp  itemid    property                            value
0         1435460400000  460429  categoryid                             1338
1         1441508400000  206783         888          1116713 960601 n277.200
2         1439089200000  395014         400  n552.000 639502 n720.000 424566
3         1431226800000   59481         790                       n15360.000
4         1431831600000  156781         917                           828513
...                 ...     ...         ...                              ...
10999994  1439694000000   86599  categoryid                              618
10999995  1435460400000  153032        1066                 n1020.000 424566
10999996  1440298800000  421788         888               35975 856003 37346
10999997  1437879600000  159792         400  n552.000 639502 n720.000 424566
10999998  1436065200000  464846         790                      n410640.000

[10999999 rows x 4 columns]

In [4]:
items_2= pd.read_csv("../data/raw/item_properties_part2.csv")
items_2

             timestamp  itemid property                             value
0        1433041200000  183478      561                            769062
1        1439694000000  132256      976                   n26.400 1135780
2        1435460400000  420307      921                   1149317 1257525
3        1431831600000  403324      917                           1204143
4        1435460400000  230701      521                            769062
...                ...     ...      ...                               ...
9275898  1433646000000  236931      929                           n12.000
9275899  1440903600000  455746        6                     150169 639134
9275900  1439694000000  347565      686                            610834
9275901  1433646000000  287231      867                            769062
9275902  1442113200000  275768      888  888666 n10800.000 746840 1318567

[9275903 rows x 4 columns]

In [ ]:
items_1.loc[(items_1.property == 'categoryid').sort_values('timestamp').head()]

             timestamp  itemid    property value
2105129  1431226800000  377283  categoryid  1016
970935   1431226800000  362999  categoryid  1016
3826363  1431226800000  373242  categoryid  1016
6363096  1431226800000  339403  categoryid  1016
4497603  1431226800000  390209  categoryid  1016